language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=gemma OPTION="lib_ignore=Wire" EXAMPLES="examples/mbino-example-blinky/*.ino"

script:
- for e in ${EXAMPLES:=examples/*/*.ino}; do
      platformio ci --board=$BOARD --lib=. ${OPTION:+--project-option="$OPTION"} $e;
  done
