language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- PLATFORMIO_CI_SRC=examples/mbino-example-analogin
- PLATFORMIO_CI_SRC=examples/mbino-example-analogin-pwmout
- PLATFORMIO_CI_SRC=examples/mbino-example-blinky PROJECT_CONF="platformio-tiny.ini"
- PLATFORMIO_CI_SRC=examples/mbino-example-error
- PLATFORMIO_CI_SRC=examples/mbino-example-i2c-lm75a
- PLATFORMIO_CI_SRC=examples/mbino-example-i2c-scanner
- PLATFORMIO_CI_SRC=examples/mbino-example-interruptin PROJECT_CONF="platformio-tiny.ini"
- PLATFORMIO_CI_SRC=examples/mbino-example-portin PROJECT_CONF="platformio-tiny.ini"
- PLATFORMIO_CI_SRC=examples/mbino-example-portout PROJECT_CONF="platformio-tiny.ini"
- PLATFORMIO_CI_SRC=examples/mbino-example-pwmout
- PLATFORMIO_CI_SRC=examples/mbino-example-rawserial
- PLATFORMIO_CI_SRC=examples/mbino-example-serial-hello
- PLATFORMIO_CI_SRC=examples/mbino-example-serial-rxirq
- PLATFORMIO_CI_SRC=examples/mbino-example-serial-stdio
- PLATFORMIO_CI_SRC=examples/mbino-example-spi-25lc040
- PLATFORMIO_CI_SRC=examples/mbino-example-spi-whoami
- PLATFORMIO_CI_SRC=examples/mbino-example-ticker PROJECT_CONF="platformio-tiny.ini"
- PLATFORMIO_CI_SRC=examples/mbino-example-time
- PLATFORMIO_CI_SRC=examples/mbino-example-timer

script:
- platformio ci --lib="." --project-conf="${PROJECT_CONF:-platformio.ini}"
- cp $PLATFORMIO_CI_SRC/*.ino $PLATFORMIO_CI_SRC/$(basename $PLATFORMIO_CI_SRC/*.ino .ino).cpp
- platformio ci --lib="." --board=nucleo_f446re
